### ISSUE TITLE
When a user is not assigned to any project, the displayed message is not as per the requirement 

### ISSUE THREAD

**Issue by ksinghprod** [NYCPlanning/labs-applicant-portal#87] opened 2020-04-13 20:43 UTC
Browser: Chrome 

Expected Result: when the user logs in with valid portal account and has a corresponding contact record which is active AND not associated to any active ZAP project with applicant or public visibility, the portal must display the following text:

“You are not currently assigned to a DCP project.”

Actual Result: the displayed text is "you do not currently have any projects that require your response" 

![image](https://user-images.githubusercontent.com/57362229/79158881-17c3b880-7da5-11ea-93eb-60bc383c132d.png)

![image](https://user-images.githubusercontent.com/57362229/79158931-2f9b3c80-7da5-11ea-8ffa-365e9270ff5d.png)

**Comment by hannahkates** [comment] 2020-04-15 12:27
Confirmed, this is the screen a user will see if they don't have any projects assigned to them in CRM. @bean75 Do you have a strong preference on language for this? We can update it to say "You are not currently assigned to a DCP project." instead.

![image.png](https://images.zenhubusercontent.com/5ca2425fd9fcf5278d7159e7/5de452b0-7500-49bb-900e-89f18c3ccd8b)

**Comment by bean75** [comment] 2020-04-15 12:33
I think the Nothing to do is fine - but update the line below to indicate that:
You are not currently assigned to any active projects. Please reach out to ZAP_Feedback_DL@planning.nyc.com if you believe this is an error.
________________________________

**Comment by hannahkates** [comment] 2020-04-20 15:49
@godfreyyeung The text for this is off. The "You are not currently assigned to a DCP project." text should only show up when the user isn't assigned to ANY projects, not just zero projects in the "to do" portion of the page. See screenshot example below. In this example, the user should see "You do not currently have any projects that require your response"

![image.png](https://images.zenhubusercontent.com/5ca2425fd9fcf5278d7159e7/b9464cb6-2c15-4c6b-a735-a31efa65c3b2)

**Comment by godfreyyeung** [comment] 2020-04-20 17:49
No To-Do projects:
```
Nothing to do.
You do not currently have any projects that require your response
```

No Active Applicant-Only or General Public projects whatsoever (Needs clarification):
```
Nothing to do.
[You are not currently assigned to a DCP project / You are not currently assigned to any active projects.] 

Please reach out to ZAP_Feedback_DL@planning.nyc.com if you believe this is an error.
```

**Comment by bean75** [comment] 2020-04-20 17:55
Nothing to do.
You are not currently assigned to any active DCP projects.

Please reach out to ZAP_Feedback_DL@planning.nyc.com if you believe this is an error.

________________________________

**Comment by ksinghprod** [comment] 2020-04-20 19:58
This issue is now fixed 

![image](https://user-images.githubusercontent.com/57362229/79794130-bdd06f00-831f-11ea-8c69-d7907f2c539b.png)

**Comment by godfreyyeung** [comment] 2020-04-21 14:34
@ksinghprod  I just deployed an update to this issue to QA and Staging. It now looks like this:

UI with these changes:

**No active DCP projects whatsoever:**
![image](https://user-images.githubusercontent.com/3311663/79790792-4ea44c00-831a-11ea-80a1-dd1ac87209ec.png)

**No Applicant projects**
![image](https://user-images.githubusercontent.com/3311663/79790945-84e1cb80-831a-11ea-9a6f-f7964ea5fb32.png)


**Applicant and Planning  projects**
![image](https://user-images.githubusercontent.com/3311663/79790862-68de2a00-831a-11ea-8346-77cb5f514c01.png)

**Comment by ksinghprod** [comment] 2020-04-21 16:09
@godfreyyeung Thanks, Will retest these and verify

**Comment by ksinghprod** [comment] 2020-04-21 20:27
this issue fixed

**Closed** 2020-04-21 20:52 UTC
Labels: Closed By QA, DCP-QA, Resolved, Sev3 Bug, User: Applicant
