### ISSUE TITLE
RWCDS: API provides actions to the front-end form

### ISSUE THREAD

**Issue by hannahkates** [NYCPlanning/labs-applicant-portal#420] opened 2020-06-17 14:57 UTC
User first loads RWCDS form and hasn't saved anything yet:
- dcp_projectaction

User has previously saved:
- RWCDS actions entity

View-only:
- RWCDS actions entity

### Attributes
What attributes should the API response include?
### Filter Logic
Which records should be included? Which should be excluded?

**Comment by trbmcginnis** [comment] 2020-06-23 18:36
Closing this because duplicate of #223

**Closed by trbmcginnis** 2020-06-23 18:36 UTC
Labels: Strategic, User: Applicant
