### ISSUE TITLE
After saving individual Applicants information on the PAS Form, when the user changes selection to organization, the organization field does not appear 

### ISSUE THREAD

**Issue by ksinghprod** [NYCPlanning/labs-applicant-portal#237] opened 2020-05-13 16:37 UTC
## Browser(s) and Device(s) observed on:
Chrome, Firefox, IE

## What should happen:
When a user enters an individual applicant's information and saves, then decides to chance the Applicant type to organization, the organization radio button should be selected and the organization field should appear 

## What happened instead:
The Organization field does not appear
(although in CRM, the applicant type becomes an authorized representative)

## How to reproduce this bug:
1 Log into Applicant Portal
2 click on the Edit Pre-Application button 
3 navigate to the Applicant team section
4 Enter details for individual and save
5 change applicant type to organization by clicking on the organization radio button 
6 the organization field will not appear (error happens here)  

![image](https://user-images.githubusercontent.com/57362229/81839957-49e84780-9516-11ea-94b9-82bc34889f0f.png)

![image](https://user-images.githubusercontent.com/57362229/81839983-553b7300-9516-11ea-895e-916f793bcc6f.png)

![image](https://user-images.githubusercontent.com/57362229/81840047-67b5ac80-9516-11ea-85dc-63b14c62d3f8.png)

**Comment by hannahkates** [comment] 2020-05-13 16:59
This is a duplicate of #214

**Comment by ksinghprod** [comment] 2020-05-15 19:38
This Issue is now fixed 

![image](https://user-images.githubusercontent.com/57362229/82089662-04687d80-96c2-11ea-88bd-e042c8720bd8.png)

**Closed** 2020-05-19 17:53 UTC
Labels: Closed By QA, DCP-QA, Resolved, Sev4 Bug, User: Applicant
