### ISSUE TITLE
Zero is auto populating in the Change in City Map, How many Change in CityMap actions? field

### ISSUE THREAD

**Issue by Hemachekuri** [NYCPlanning/labs-applicant-portal#265] opened 2020-05-15 16:40 UTC
## Browser(s) 
IE Browser and chrome

## What should happen:
Upon selection of Change in City Map (for the second time, after deleting the data entered prior to, see repro steps) the How many Change in CityMap actions? field should be null/blank

## What happened instead:
After selecting Change in City Map the, How many Change in CityMap actions? field was now repopulated with a 0
## How to reproduce this bug:
1 Log Into Applicant Portal
2 Click on the Edit Pre-Application Statement button
3 Navigate to Proposed Land Use action section, select for example, change in city mad form the drop down
4 Enter data into the Change in How many "Change in CityMap actions?" field and save 
5 Now x out/delete then Change in City Map selection 
6 From the drop down select Change in City Map again (error can be seen here) How many Change in City Map actions? will no have 0

-I have edited this @Hemachekuri 

![image](https://user-images.githubusercontent.com/63460627/82074106-3ff64e00-96a8-11ea-8d09-d814d38da77d.png)

![image](https://user-images.githubusercontent.com/63460627/82074173-5a302c00-96a8-11ea-95f6-3ccd834a5746.png)

![image](https://user-images.githubusercontent.com/63460627/82074530-ea6e7100-96a8-11ea-8ae7-1e8f084df39f.png)

![image](https://user-images.githubusercontent.com/63460627/82074612-07a33f80-96a9-11ea-87c5-ab4626d51b87.png)

![image](https://user-images.githubusercontent.com/63460627/82074676-1e499680-96a9-11ea-9add-ccd12890fa34.png)

**Comment by hannahkates** [comment] 2020-05-15 17:06
@Hemachekuri I think you pasted in the wrong steps to reproduce? They don't mention the zero.

I think this problem will be solved by #264. @trbmcginnis can you confirm that Change in City Map no long pre-populates with zero? If a user adds a Change in City Map action, it should default to 1 (not shown to the user) and send 1 to the database.

**Comment by ksinghprod** [comment] 2020-05-15 17:28
Hi @hannahkates, I have edited the issue and repro steps. Please let me know if anything is still unclear

CC @Hemachekuri

**Comment by hannahkates** [comment] 2020-05-15 17:30
Thanks @ksinghprod !

**Comment by andycochran** [comment] 2020-05-15 19:08
This should be addressed in @trbmcginnis's PR: #264.

**Comment by trbmcginnis** [comment] 2020-05-15 20:26
Solved in PR #264

https://github.com/NYCPlanning/labs-applicant-portal/pull/264

**Comment by ksinghprod** [comment] 2020-05-18 19:36
Hi @hannahkates, although this issue is fixed, if a user selects for example, Zoning Certification from the Proposed Land Use Acton drop down and then deletes it. Then Saves. the CRM side for the Zoning Certification field gets auto populated with a 0. and as result the conditional required fields appear . 

Should I close this issue and raise new issue for that, or just keep this one open?

**Comment by hannahkates** [comment] 2020-05-19 01:30
That kind of seems like a CRM bug if it treats zero as a yes. I think we make our app send NULL instead of 0.

**Comment by hannahkates** [comment] 2020-05-19 15:57
Increasing the severity to Sev3 because it keeps the form from saving properly.

**Comment by trbmcginnis** [comment] 2020-05-19 16:07
Count field was originally being set to `0` when a user deleted an action. PR #282 merged this morning updated this to be set to `null` when a user deleted an action. Double checking that this has the appropriate CRM response. 

https://github.com/NYCPlanning/labs-applicant-portal/pull/282/files#diff-555a09f8c5dd22aa6d6d82a8c4f78d85

**Comment by trbmcginnis** [comment] 2020-05-19 16:22
Confirmed PR #282 provided the needed updates -- deleting actions no longer sets them to zero in CRM, not they are just `null`

![Screen Shot 2020-05-19 at 11.21.52 AM.png](https://images.zenhubusercontent.com/5ca36b1555cfe32f2f66b411/6b901563-72c9-43ed-89de-0d8902b4c876)

**Comment by ksinghprod** [comment] 2020-05-19 17:58
This issue is now fixed @Hemachekuri 

![image](https://user-images.githubusercontent.com/57362229/82361178-83b6c380-99d8-11ea-93b0-9e6be45d1c42.png)


![image](https://user-images.githubusercontent.com/57362229/82361287-a47f1900-99d8-11ea-9d09-a45ed92b656f.png)

![image](https://user-images.githubusercontent.com/57362229/82361392-c9738c00-99d8-11ea-9490-c0c920517fe7.png)

**Closed by ksinghprod** 2020-05-19 17:58 UTC
Labels: DCP-QA, Resolved, Sev3 Bug, User: Applicant
