### ISSUE TITLE
The Submit button is not working 

### ISSUE THREAD

**Issue by Hemachekuri** [NYCPlanning/labs-applicant-portal#263] opened 2020-05-15 16:27 UTC
## Browser(s) 
IE Browser and chrome

**EDIT: THIS ISSUE SEEMS TO BE HAPPENING WHEN THE USER UPLOADS A DOCUMENT/FILE**

## What should happen:
User added BBL, then Proposed action items, and then saved and clicked on submit, upon submit, it should get submitted (or any other edit)
## What happened instead:
User added BBL, then Proposed action items, and then saved and clicked on submit, upon submit, it is not getting submitted or any validation/Notification message is displayed. 
## How to reproduce this bug:
1. Log Into Applicant Portal
2. Click on the Edit Pre-Application Statement button
3. Navigate BBL section, add BBL, then go to Proposed action items, select on item form drop down, input the text as needed and click on save and  then on submit. It should be submitted or if any other fields are need, validation message or notification why user not able to submit should displayed.
![image](https://user-images.githubusercontent.com/63460627/82073545-65cf2300-96a7-11ea-9dab-9c81f2af2b9f.png)

**Comment by ksinghprod** [comment] 2020-05-15 17:32
@Hemachekuri  I edited this issue

**Comment by allthesignals** [comment] 2020-05-15 19:19
@ksinghprod @Hemachekuri thanks! can you share a link to this package, please?

**Comment by allthesignals** [comment] 2020-05-15 19:39
I think I need more info. I can't reproduce this yet. Can you find out which project action you selected?

link: https://qa.applicant-portal.planninglabs.nyc/packages/9ada046a-2095-ea11-a811-001dd8309f0e/edit

**Comment by ksinghprod** [comment] 2020-05-15 19:55
@allthesignals @Hemachekuri 

This issue is now fixed, 
![image](https://user-images.githubusercontent.com/57362229/82090943-8063c500-96c4-11ea-9363-b0272fec3eeb.png)

**Comment by ksinghprod** [comment] 2020-05-15 21:11
This issue is back, it happens whens the user uploads a document/file

**Comment by allthesignals** [comment] 2020-05-16 14:40
Can you check again? @ksinghprod. I think it was due to a missing env variable?

**Comment by ksinghprod** [comment] 2020-05-18 21:55
This issue is now fixed 
@Hemachekuri 

![image](https://user-images.githubusercontent.com/57362229/82263386-c58c2f00-9930-11ea-9a83-a3dc29bc31fc.png)

**Closed by ksinghprod** 2020-05-18 21:55 UTC
Labels: DCP-QA, Sev2 Bug, User: Applicant
