### ISSUE TITLE
Update deployment pipeline for QA team

### ISSUE THREAD

**Issue by hannahkates** [NYCPlanning/labs-applicant-portal#14] opened 2020-03-12 15:53 UTC
## User story:
As a QA analyst, I need an isolated, stable environment (no unannounced code changes) in which to perform QA testing.

Code should be manually deployed from Labs' development environment into the QA Team's environment at agreed upon intervals when code changes are ready for testing.

- Create branches on front end and API
- Rename branches
- Create netlify deployments and URLs

Diagram: https://docs.google.com/presentation/d/1rfC-jxB5Rh-d8gnP9CmDM_iVbeuKJ0ppDPSYLmz6HWI/edit#slide=id.g715440f704_0_0

**Comment by bfreeds** [comment] 2020-04-07 15:30
From @hannahkates, we need five environments / deployment pipelines:

| Git Branch        | Domain           | CRM Environment  |
| ------------- |-------------:| -----|
| feature branches      | (Netlify auto generated) | UAT2 |
| develop      | develop.applicants.planning.nyc.gov      |   UAT2 |
| qa | qa.applicants.planning.nyc.gov      |    UAT2 |
| staging | staging.applicants.planning.nyc.gov      |    UAT |
| master | applicants.planning.nyc.gov      |    PROD|

Our code will flow:
`feature` > `develop` > `qa` > `staging` > `master`

**Comment by bfreeds** [comment] 2020-04-07 15:33
- [ ] Domains & Subdomains Created
- [ ] Heroku Pipelines Configured for API Server deployments
- [ ] Netlify Configuration for frontend web app

**Comment by bfreeds** [comment] 2020-04-07 17:48
Created Heroku app in the "staging" pipeline for qa.  I don't see a way in Heroku to change the pipeline configurations from their existing buckets ("Review," "Staging", "Production"), so this will be an app within their "Staging" pipeline that auto deploys from the `qa` branch.   

I kept all the same config from the current staging deploy except for the `CRM_HOST` variable, changing `uat2` => `uat` in the url.

**Comment by bfreeds** [comment] 2020-04-07 22:08
Getting the user-friendly subdomains setup I think depends on #57.  In the meantime, we can use the default netlify URLs for qa.  

Backend API deployment pipelines are configured in Heroku.
Frontend deploys will be configured when #66 is merged.

Then we'll need to make a PR to merge `develop` => `qa` to trigger the initial deploy and make sure the qa team has the most up-to-date code to test from.  The URL will be:
**qa--applicant-portal.netlify.com**

After that happens and I can confirm that the deployments & urls are as expected I'll update the README with deployment documentation.

**Comment by allthesignals** [comment] 2020-04-08 00:22
@bfreeds the only issue with using the netlify domains is that NYC.ID won't allow a redirect back to netlify because it's not on the whitelist. I could add it, but also, [here](https://docs.google.com/document/d/15bHyO4FklVMVUYaRyzuf4EhveCg7sVMlgeAwlW_VF_o/edit#heading=h.qzvvxgx5yn59) are the instructions for dealing with adding custom subdomains to planninglabs. Basically: it's a matter of configuring our conf.d file in the nginx server configuration. Happy to talk through it at any time.

**Comment by bfreeds** [comment] 2020-04-09 20:23
[qa.applicant-portal.planninglabs.nyc](qa.applicant-portal.planninglabs.nyc) setup and good to go.  Worked with @allthesignals to correctly configure NYC ID service account for the log-in process. 

Have not configured all the subdomains as outlined in earlier comment, but closing this issue as the QA deployment pipeline is confirmed to be working.

**Closed by bfreeds** 2020-04-09 20:23 UTC
Labels: New Feature, User: Applicant
